<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FasilitasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('fasilitas')->insert([
            ['id_fasilitas' => 'F001', 'id_pariwisata' => 'P001', 'nama_fasilitas' => 'Hotel Nala', 'lokasi' => 'Jalan Pantai No. 1, Kota Bengkulu', 'jenis' => 'Hotel', 'deskripsi' => 'Hotel Nala adalah pilihan akomodasi yang sempurna bagi para wisatawan yang ingin menikmati suasana tepi laut. Dikenal karena kenyamanannya, hotel ini menawarkan berbagai fasilitas lengkap seperti kolam renang, spa, dan restoran dengan pemandangan laut yang menakjubkan. Setiap kamar dilengkapi dengan balkon pribadi, memungkinkan tamu untuk menikmati pemandangan matahari terbenam yang spektakuler.', 'latitude' => '-3.7950', 'longitude' => '102.2675'],
            ['id_fasilitas' => 'F002', 'id_pariwisata' => 'P001', 'nama_fasilitas' => 'Restoran Ocean Breeze', 'lokasi' => 'Jalan Pantai No. 2, Kota Bengkulu', 'jenis' => 'Restoran', 'deskripsi' => 'Ocean Breeze adalah restoran yang menawarkan pengalaman bersantap yang tak terlupakan dengan pemandangan laut yang luas. Menyajikan hidangan laut segar yang ditangkap langsung dari perairan sekitar, restoran ini juga memiliki menu lokal khas Bengkulu yang menggugah selera. Dengan suasana yang nyaman dan pelayanan yang ramah, Ocean Breeze adalah tempat yang ideal untuk makan siang atau malam bersama keluarga dan teman.', 'latitude' => '-3.7955', 'longitude' => '102.2680'],
            ['id_fasilitas' => 'F003', 'id_pariwisata' => 'P002', 'nama_fasilitas' => 'Grand Pasir Putih Hotel', 'lokasi' => 'Jalan Pasir Putih No. 5, Kota Bengkulu', 'jenis' => 'Hotel', 'deskripsi' => 'Grand Pasir Putih Hotel adalah hotel mewah yang menawarkan akses langsung ke pantai dengan fasilitas yang dirancang untuk memberikan kenyamanan maksimal. Dengan kolam renang yang luas, spa yang lengkap, dan restoran yang menyajikan berbagai hidangan internasional, hotel ini menjadi pilihan utama bagi wisatawan yang mencari pengalaman menginap yang istimewa. Setiap kamar dirancang dengan gaya modern dan dilengkapi dengan semua kenyamanan yang diperlukan untuk membuat tamu merasa seperti di rumah.', 'latitude' => '-3.8030', 'longitude' => '102.2640'],
            ['id_fasilitas' => 'F004', 'id_pariwisata' => 'P002', 'nama_fasilitas' => 'Warung Makan Jaya', 'lokasi' => 'Jalan Raya Jakat No. 4, Kota Bengkulu', 'jenis' => 'Restoran', 'deskripsi' => 'Warung Makan Jaya adalah tempat yang sempurna untuk menikmati hidangan ikan bakar dan hidangan laut khas Bengkulu. Dengan suasana yang sederhana dan hangat, warung ini menjadi favorit di kalangan penduduk lokal dan wisatawan. Menu yang ditawarkan menggunakan bahan-bahan segar dan bumbu tradisional, memberikan cita rasa autentik yang sulit dilupakan. Nikmati pengalaman bersantap yang dekat dengan budaya lokal sambil menikmati pemandangan sekitar.', 'latitude' => '-3.8040', 'longitude' => '102.2650'],
            ['id_fasilitas' => 'F005', 'id_pariwisata' => 'P003', 'nama_fasilitas' => 'Kafe Malabero', 'lokasi' => 'Jalan Malabero No. 9, Kota Bengkulu', 'jenis' => 'Restoran', 'deskripsi' => 'Kafe Malabero adalah kafe modern yang menawarkan berbagai pilihan kopi berkualitas tinggi dan makanan ringan yang menggugah selera. Dengan suasana yang nyaman dan desain interior yang menarik, kafe ini adalah tempat yang ideal untuk bersantai sambil menikmati pemandangan Pantai Malabero. Baik untuk pertemuan bisnis, berkumpul dengan teman, atau sekadar menikmati waktu sendiri dengan buku, Kafe Malabero selalu siap menyambut Anda.', 'latitude' => '-3.8035', 'longitude' => '102.2665'],
            ['id_fasilitas' => 'F006', 'id_pariwisata' => 'P004', 'nama_fasilitas' => 'Souvenir Shop Bengkulu', 'lokasi' => 'Jalan Tapak Paderi No. 11, Kota Bengkulu', 'jenis' => 'Oleh-oleh', 'deskripsi' => 'Souvenir Shop Bengkulu adalah tempat yang tepat untuk menemukan berbagai kerajinan tangan khas Bengkulu. Toko ini menawarkan beragam barang unik, mulai dari kain batik, perhiasan tradisional, hingga barang-barang kerajinan yang dibuat oleh pengrajin lokal. Dengan suasana yang ramah dan pelayanan yang baik, Anda dapat dengan mudah menemukan oleh-oleh yang sempurna untuk dibawa pulang sebagai kenang-kenangan dari perjalanan Anda.', 'latitude' => '-3.7955', 'longitude' => '102.2605'],
            ['id_fasilitas' => 'F007', 'id_pariwisata' => 'P004', 'nama_fasilitas' => 'Masjid Agung At-Taqwa', 'lokasi' => 'Jalan Raya Masjid Agung No. 1, Kota Bengkulu', 'jenis' => 'Tempat Ibadah', 'deskripsi' => 'Masjid Agung At-Taqwa adalah masjid terbesar di Bengkulu yang menawarkan fasilitas ibadah yang nyaman dan arsitektur yang megah. Dengan desain yang indah dan lingkungan yang tenang, masjid ini menjadi tempat yang ideal untuk beribadah dan merenung. Selain itu, masjid ini sering menjadi lokasi berbagai kegiatan keagamaan dan sosial, menjadikannya pusat komunitas bagi umat Muslim di Bengkulu.', 'latitude' => '-3.8610', 'longitude' => '102.2630'],
            ['id_fasilitas' => 'F008', 'id_pariwisata' => 'P005', 'nama_fasilitas' => 'Hotel Marlborough', 'lokasi' => 'Jalan Benteng No. 3, Kota Bengkulu', 'jenis' => 'Hotel', 'deskripsi' => 'Hotel Marlborough adalah akomodasi yang menawarkan kenyamanan dan akses mudah ke Benteng Marlborough, sebuah situs sejarah penting di Bengkulu. Hotel ini dilengkapi dengan fasilitas modern, termasuk restoran, kolam renang, dan ruang pertemuan. Setiap kamar dirancang untuk memberikan kenyamanan maksimal, menjadikannya pilihan yang ideal bagi wisatawan yang ingin menjelajahi sejarah dan budaya Bengkulu.', 'latitude' => '-3.8035', 'longitude' => '102.2655'],
            ['id_fasilitas' => 'F009', 'id_pariwisata' => 'P006', 'nama_fasilitas' => 'Restoran Colonial', 'lokasi' => 'Jalan Benteng No. 5, Kota Bengkulu', 'jenis' => 'Restoran', 'deskripsi' => 'Restoran Colonial menawarkan pengalaman bersantap yang unik dengan konsep kolonial yang elegan. Menyajikan hidangan tradisional dan internasional, restoran ini menjadi tempat yang sempurna untuk menikmati makanan dalam suasana yang nyaman dan mewah. Dengan pelayanan yang ramah dan profesional, setiap kunjungan ke restoran ini akan menjadi pengalaman yang tak terlupakan.', 'latitude' => '-3.8040', 'longitude' => '102.2660'],
            ['id_fasilitas' => 'F010', 'id_pariwisata' => 'P007', 'nama_fasilitas' => 'Taman Hiburan Rakyat', 'lokasi' => 'Jalan Raya No. 4, Kota Bengkulu', 'jenis' => 'Oleh-oleh', 'deskripsi' => 'Taman Hiburan Rakyat adalah tempat yang menyenangkan bagi keluarga dengan berbagai permainan untuk anak-anak. Taman ini dilengkapi dengan area bermain yang aman dan nyaman, serta berbagai fasilitas untuk bersantai. Tempat ini menjadi pilihan yang tepat untuk menghabiskan waktu bersama keluarga dan teman-teman, menjadikan setiap kunjungan penuh dengan keceriaan dan kebahagiaan.', 'latitude' => '-3.8600', 'longitude' => '102.2670'],
            ['id_fasilitas' => 'F011', 'id_pariwisata' => 'P008', 'nama_fasilitas' => 'Kedai Kopi Bengkulu', 'lokasi' => 'Jalan Kopi No. 3, Kota Bengkulu', 'jenis' => 'Restoran', 'deskripsi' => 'Kedai Kopi Bengkulu terkenal dengan pilihan kopi lokal yang berkualitas tinggi dan suasana yang hangat. Tempat ini sangat cocok untuk berkumpul dengan teman-teman atau sekadar menikmati waktu sendiri dengan secangkir kopi. Dengan berbagai pilihan makanan ringan yang lezat, Kedai Kopi Bengkulu menawarkan pengalaman bersantai yang sempurna di tengah kesibukan kota.', 'latitude' => '-3.8500', 'longitude' => '102.3050'],
            ['id_fasilitas' => 'F012', 'id_pariwisata' => 'P009', 'nama_fasilitas' => 'Klinik Kesehatan Pantai', 'lokasi' => 'Jalan Pantai No. 6, Kota Bengkulu', 'jenis' => 'Hotel', 'deskripsi' => 'Klinik Kesehatan Pantai adalah fasilitas medis yang dirancang untuk memberikan perawatan kesehatan yang cepat dan efisien bagi wisatawan. Dengan tenaga medis yang profesional dan peralatan medis yang lengkap, klinik ini siap membantu wisatawan yang membutuhkan perawatan kesehatan selama berada di Bengkulu. Lokasinya yang strategis dekat dengan pantai membuatnya mudah diakses oleh pengunjung.', 'latitude' => '-3.8580', 'longitude' => '102.3190'],
            ['id_fasilitas' => 'F013', 'id_pariwisata' => 'P010', 'nama_fasilitas' => 'Alun-Alun Resto', 'lokasi' => 'Jalan Alun-Alun No. 3, Kota Bengkulu', 'jenis' => 'Restoran', 'deskripsi' => 'Alun-Alun Resto adalah tempat makan yang menyajikan berbagai hidangan lokal dan internasional dalam suasana yang nyaman dan elegan. Dengan desain interior yang modern dan pelayanan yang ramah, resto ini menjadi pilihan yang tepat untuk makan bersama keluarga atau merayakan momen spesial. Menu yang ditawarkan selalu menggunakan bahan-bahan segar dan berkualitas tinggi.', 'latitude' => '-3.8505', 'longitude' => '102.3065'],
            ['id_fasilitas' => 'F014', 'id_pariwisata' => 'P011', 'nama_fasilitas' => 'Grand City Hotel', 'lokasi' => 'Jalan Raya No. 8, Kota Bengkulu', 'jenis' => 'Hotel', 'deskripsi' => 'Grand City Hotel adalah hotel bintang lima yang menawarkan fasilitas premium untuk para tamu. Dengan lokasi yang strategis, hotel ini cocok untuk pebisnis dan wisatawan. Fasilitas yang tersedia termasuk ruang pertemuan, restoran dengan menu internasional, dan layanan spa yang menenangkan. Setiap kamar dirancang dengan elegan untuk memberikan kenyamanan maksimal.', 'latitude' => '-3.8555', 'longitude' => '102.3075'],
            ['id_fasilitas' => 'F015', 'id_pariwisata' => 'P012', 'nama_fasilitas' => 'Masjid Raya Al-Muqarrabin', 'lokasi' => 'Jalan Al-Muqarrabin No. 1, Kota Bengkulu', 'jenis' => 'Tempat Ibadah', 'deskripsi' => 'Masjid Raya Al-Muqarrabin adalah masjid besar yang memiliki ruang ibadah yang luas dan fasilitas modern untuk kenyamanan jamaah. Dengan arsitektur yang megah dan lingkungan yang tenang, masjid ini menjadi tempat yang ideal untuk beribadah dan berkumpul dengan komunitas. Selain itu, masjid ini sering mengadakan berbagai kegiatan keagamaan dan sosial.', 'latitude' => '-3.8605', 'longitude' => '102.3160'],
            ['id_fasilitas' => 'F016', 'id_pariwisata' => 'P013', 'nama_fasilitas' => 'Pasar Tradisional Pantai', 'lokasi' => 'Jalan Pasar No. 9, Kota Bengkulu', 'jenis' => 'Oleh-oleh', 'deskripsi' => 'Pasar Tradisional Pantai adalah tempat yang menawarkan berbagai barang kerajinan tangan, makanan khas, dan oleh-oleh dari Bengkulu. Dengan suasana yang ramai dan penuh warna, pasar ini menjadi tempat yang tepat untuk merasakan budaya lokal dan menemukan barang-barang unik. Anda dapat menemukan berbagai produk lokal yang tidak hanya menarik tetapi juga berkualitas.', 'latitude' => '-3.8500', 'longitude' => '102.3100'],
            ['id_fasilitas' => 'F017', 'id_pariwisata' => 'P014', 'nama_fasilitas' => 'Taman Kota Bengkulu', 'lokasi' => 'Jalan Kota No. 2, Kota Bengkulu', 'jenis' => 'Oleh-oleh', 'deskripsi' => 'Taman Kota Bengkulu adalah taman yang dilengkapi dengan jalur jogging, area bermain anak, dan taman hijau untuk bersantai. Tempat ini menjadi pilihan yang populer bagi warga lokal dan pengunjung untuk menikmati waktu luang. Dengan suasana yang sejuk dan asri, taman ini juga sering digunakan untuk berbagai kegiatan komunitas dan acara keluarga, menjadikannya tempat yang ideal untuk bersantai sambil menikmati keindahan alam.', 'latitude' => '-3.8605', 'longitude' => '102.3050'],
            ['id_fasilitas' => 'F018', 'id_pariwisata' => 'P015', 'nama_fasilitas' => 'Taman Remaja', 'lokasi' => 'Jalan Remaja No. 4, Kota Bengkulu', 'jenis' => 'Tempat Ibadah', 'deskripsi' => 'Taman Remaja adalah taman yang dilengkapi dengan fasilitas olahraga dan area hijau, menjadi tempat yang populer bagi warga lokal dan pengunjung untuk bersantai dan berolahraga. Dengan berbagai fasilitas seperti lapangan basket dan jogging track, taman ini menawarkan suasana yang menyegarkan dan menjadi tempat berkumpul yang ideal bagi anak muda dan keluarga.', 'latitude' => '-3.8600', 'longitude' => '102.3060'],
            ['id_fasilitas' => 'F019', 'id_pariwisata' => 'P016', 'nama_fasilitas' => 'Hotel Palmera', 'lokasi' => 'Jalan Raya No. 7, Kota Bengkulu', 'jenis' => 'Hotel', 'deskripsi' => 'Hotel Palmera adalah akomodasi yang menawarkan fasilitas kamar yang nyaman dan layanan kelas atas. Dengan lokasi yang strategis, hotel ini memberikan akses mudah ke berbagai destinasi wisata di Bengkulu. Fasilitas yang tersedia termasuk restoran, kolam renang, dan layanan spa, menjadikannya pilihan yang ideal bagi wisatawan yang ingin menikmati kenyamanan dan kemewahan selama menginap.', 'latitude' => '-3.8590', 'longitude' => '102.3105'],
            ['id_fasilitas' => 'F020', 'id_pariwisata' => 'P017', 'nama_fasilitas' => 'Restoran Makanan Laut Bengkulu', 'lokasi' => 'Jalan Laut No. 3, Kota Bengkulu', 'jenis' => 'Restoran', 'deskripsi' => 'Restoran Makanan Laut Bengkulu menyajikan hidangan laut segar yang langsung diambil dari pantai Bengkulu. Dengan suasana yang santai dan pemandangan laut yang menakjubkan, restoran ini sangat populer di kalangan wisatawan dan penduduk lokal. Menu yang ditawarkan mencakup berbagai pilihan hidangan laut yang lezat, menjadikannya tempat yang sempurna untuk menikmati makanan sambil menikmati keindahan alam.', 'latitude' => '-3.8620', 'longitude' => '102.3115'],
            ['id_fasilitas' => 'F021', 'id_pariwisata' => 'P018', 'nama_fasilitas' => 'Toko Souvenir Pantai', 'lokasi' => 'Jalan Pantai No. 6, Kota Bengkulu', 'jenis' => 'Oleh-oleh', 'deskripsi' => 'Toko Souvenir Pantai adalah tempat yang menawarkan berbagai barang khas Bengkulu, termasuk kain batik, kerajinan tangan, dan perhiasan tradisional. Dengan suasana yang ramah dan pelayanan yang baik, Anda dapat menemukan oleh-oleh yang sempurna untuk dibawa pulang sebagai kenang-kenangan dari perjalanan Anda. Toko ini juga sering menjadi tempat bagi wisatawan untuk belajar lebih banyak tentang budaya lokal.', 'latitude' => '-3.8635', 'longitude' => '102.3150'],
            ['id_fasilitas' => 'F022', 'id_pariwisata' => 'P019', 'nama_fasilitas' => 'Masjid Raya Bengkulu', 'lokasi' => 'Jalan Raya No. 2, Kota Bengkulu', 'jenis' => 'Tempat Ibadah', 'deskripsi' => 'Masjid Raya Bengkulu terletak di pusat kota dan menjadi tempat ibadah utama bagi penduduk Bengkulu. Dengan arsitektur yang megah dan fasilitas yang nyaman, masjid ini sering digunakan untuk berbagai kegiatan keagamaan dan sosial. Lingkungan yang tenang dan damai menjadikannya tempat yang ideal untuk beribadah dan merenung.', 'latitude' => '-3.8605', 'longitude' => '102.3180'],
            ['id_fasilitas' => 'F023', 'id_pariwisata' => 'P020', 'nama_fasilitas' => 'Kedai Kopi Rakyat', 'lokasi' => 'Jalan Kopi No. 5, Kota Bengkulu', 'jenis' => 'Restoran', 'deskripsi' => 'Kedai Kopi Rakyat adalah tempat yang sempurna untuk menikmati berbagai varian kopi lokal yang disajikan dalam suasana santai. Dengan desain yang sederhana namun nyaman, kedai ini menjadi pilihan favorit bagi para pecinta kopi dan mereka yang ingin bersantai sambil menikmati waktu bersama teman atau keluarga. Menu yang ditawarkan mencakup berbagai pilihan kopi, teh, dan makanan ringan yang lezat, menjadikannya tempat yang ideal untuk bersantai setelah seharian beraktivitas.', 'latitude' => '-3.8595', 'longitude' => '102.3090'],
            ['id_fasilitas' => 'F024', 'id_pariwisata' => 'P021', 'nama_fasilitas' => 'Restoran Sederhana', 'lokasi' => 'Jalan Sederhana No. 4, Kota Bengkulu', 'jenis' => 'Restoran', 'deskripsi' => 'Restoran Sederhana menyajikan masakan padang dengan cita rasa autentik yang menggugah selera. Dengan pelayanan yang ramah dan suasana yang nyaman, restoran ini menjadi tempat yang ideal untuk makan bersama keluarga. Menu yang ditawarkan menggunakan bahan-bahan segar dan resep tradisional, memberikan pengalaman bersantap yang memuaskan bagi setiap pengunjung.', 'latitude' => '-3.8615', 'longitude' => '102.3075'],
            ['id_fasilitas' => 'F025', 'id_pariwisata' => 'P022', 'nama_fasilitas' => 'Hotel Pacific', 'lokasi' => 'Jalan Pasifik No. 9, Kota Bengkulu', 'jenis' => 'Hotel', 'deskripsi' => 'Hotel Pacific adalah hotel berbintang yang menawarkan berbagai fasilitas termasuk restoran, kolam renang, dan ruang pertemuan. Dengan lokasi yang strategis, hotel ini cocok untuk wisatawan dan pebisnis yang mencari kenyamanan dan kemudahan akses ke berbagai tempat menarik di Bengkulu. Setiap kamar dirancang dengan elegan dan dilengkapi dengan semua kenyamanan modern untuk memastikan pengalaman menginap yang menyenangkan.', 'latitude' => '-3.8605', 'longitude' => '102.3150'],
            ['id_fasilitas' => 'F026', 'id_pariwisata' => 'P023', 'nama_fasilitas' => 'Toko Batik Besurek', 'lokasi' => 'Jalan Batik No. 2, Kota Bengkulu', 'jenis' => 'Oleh-oleh', 'deskripsi' => 'Toko Batik Besurek adalah tempat yang menjual berbagai produk batik khas Bengkulu, termasuk pakaian, aksesori, dan kain tradisional yang dibuat dengan tangan. Dengan suasana yang ramah dan pelayanan yang baik, Anda dapat menemukan oleh-oleh yang sempurna untuk dibawa pulang sebagai kenang-kenangan dari perjalanan Anda. Toko ini juga sering menjadi tempat bagi wisatawan untuk belajar lebih banyak tentang seni batik dan proses pembuatannya.', 'latitude' => '-3.8590', 'longitude' => '102.3165'],
            ['id_fasilitas' => 'F027', 'id_pariwisata' => 'P024', 'nama_fasilitas' => 'Warung Makan Keluarga', 'lokasi' => 'Jalan Makan No. 3, Kota Bengkulu', 'jenis' => 'Restoran', 'deskripsi' => 'Warung Makan Keluarga adalah tempat yang menyediakan berbagai menu rumahan khas Bengkulu, dari ikan bakar hingga sayur mayur yang segar. Dengan suasana yang hangat dan ramah, warung ini menjadi pilihan yang tepat untuk menikmati makanan bersama keluarga. Menu yang ditawarkan selalu menggunakan bahan-bahan segar dan resep tradisional, memberikan cita rasa yang autentik dan memuaskan.', 'latitude' => '-3.8580', 'longitude' => '102.3195'],
            ['id_fasilitas' => 'F028', 'id_pariwisata' => 'P025', 'nama_fasilitas' => 'Hotel Paradise', 'lokasi' => 'Jalan Raya No. 5, Kota Bengkulu', 'jenis' => 'Hotel', 'deskripsi' => 'Hotel Paradise adalah hotel nyaman dan terjangkau dengan berbagai fasilitas bagi wisatawan yang ingin menjelajahi Bengkulu. Dengan pelayanan yang ramah dan fasilitas yang lengkap, hotel ini menjadi pilihan yang ideal untuk para pelancong. Setiap kamar dirancang untuk memberikan kenyamanan maksimal, menjadikannya tempat yang sempurna untuk beristirahat setelah seharian beraktivitas.', 'latitude' => '-3.8600', 'longitude' => '102.3085'],
            ['id_fasilitas' => 'F029', 'id_pariwis ata' => 'P026', 'nama_fasilitas' => 'Kedai Kopi Damar', 'lokasi' => 'Jalan Damar No. 4, Kota Bengkulu', 'jenis' => 'Restoran', 'deskripsi' => 'Kedai Kopi Damar adalah tempat yang menyajikan berbagai pilihan kopi lokal dan minuman lainnya dengan suasana yang nyaman dan cocok untuk bersantai. Dengan desain yang sederhana namun menarik, kedai ini menjadi pilihan favorit bagi para pecinta kopi dan mereka yang ingin menikmati waktu santai. Menu yang ditawarkan mencakup berbagai pilihan kopi, teh, dan makanan ringan yang lezat, menjadikannya tempat yang ideal untuk bersantai setelah seharian beraktivitas.', 'latitude' => '-3.8602', 'longitude' => '102.3175'],
            ['id_fasilitas' => 'F030', 'id_pariwisata' => 'P027', 'nama_fasilitas' => 'Restoran Seruni', 'lokasi' => 'Jalan Seruni No. 8, Kota Bengkulu', 'jenis' => 'Restoran', 'deskripsi' => 'Restoran Seruni menyajikan hidangan khas Bengkulu dengan pilihan menu lokal yang lezat dan suasana yang menyenangkan untuk makan bersama keluarga. Dengan pelayanan yang ramah dan suasana yang nyaman, restoran ini menjadi tempat yang ideal untuk menikmati makanan sambil berkumpul dengan orang-orang terkasih. Menu yang ditawarkan selalu menggunakan bahan-bahan segar dan berkualitas tinggi, memberikan pengalaman bersantap yang memuaskan bagi setiap pengunjung.', 'latitude' => '-3.8598', 'longitude' => '102.3160'],
            ['id_fasilitas' => 'F031', 'id_pariwisata' => 'P028', 'nama_fasilitas' => 'Hotel Nala', 'lokasi' => 'Jalan Pantai No. 10, Kota Bengkulu', 'jenis' => 'Hotel', 'deskripsi' => 'Hotel Nala adalah akomodasi yang terletak dekat dengan Pantai Panjang, menawarkan fasilitas lengkap untuk kenyamanan tamu yang berkunjung. Dengan pemandangan laut yang menakjubkan dan akses mudah ke pantai, hotel ini menjadi pilihan yang sempurna bagi wisatawan yang ingin menikmati keindahan alam. Setiap kamar dilengkapi dengan fasilitas modern dan pelayanan yang ramah, menjadikan pengalaman menginap Anda tak terlupakan.', 'latitude' => '-3.8608', 'longitude' => '102.3140'],
            ['id_fasilitas' => 'F032', 'id_pariwisata' => 'P029', 'nama_fasilitas' => 'Warung Kopi Kampung', 'lokasi' => 'Jalan Kopi Raya, Kota Bengkulu', 'jenis' => 'Restoran', 'deskripsi' => 'Warung Kopi Kampung menawarkan suasana tradisional yang nyaman, menyajikan kopi khas Bengkulu yang nikmat dengan berbagai makanan ringan. Tempat ini menjadi pilihan yang tepat untuk bersantai sambil menikmati secangkir kopi dan berbincang dengan teman-teman. Dengan pelayanan yang ramah dan suasana yang hangat, Warung Kopi Kampung adalah tempat yang ideal untuk menikmati waktu santai.', 'latitude' => '-3.8610', 'longitude' => '102.3190'],
            ['id_fasilitas' => 'F033', 'id_pariwisata' => 'P030', 'nama_fasilitas' => 'Toko Oleh-oleh Bengkulu', 'lokasi' => 'Jalan Raya No. 6, Kota Bengkulu', 'jenis' => 'Oleh-oleh', 'deskripsi' => 'Toko Oleh-oleh Bengkulu menyediakan berbagai oleh-oleh khas Bengkulu seperti kain batik, kerajinan tangan, dan perhiasan tradisional. Dengan suasana yang ramah dan pelayanan yang baik, Anda dapat menemukan oleh-oleh yang sempurna untuk dibawa pulang sebagai kenang-kenangan dari perjalanan Anda. Toko ini juga sering menjadi tempat bagi wisatawan untuk belajar lebih banyak tentang budaya lokal dan kerajinan tangan yang ada di Bengkulu.', 'latitude' => '-3.8605', 'longitude' => '102.3185'],
            ['id_fasilitas' => 'F034', 'id_pariwisata' => 'P031', 'nama_fasilitas' => 'Masjid Raya Pantai', 'lokasi' => 'Jalan Raya Pantai No. 3, Kota Bengkulu', 'jenis' => 'Tempat Ibadah', 'deskripsi' => 'Masjid Raya Pantai adalah masjid besar yang terletak di dekat pantai, menjadi tempat ibadah utama bagi umat Muslim di Bengkulu. Dengan arsitektur yang megah dan lingkungan yang tenang, masjid ini sering digunakan untuk berbagai kegiatan keagamaan dan sosial. Fasilitas yang nyaman dan akses yang mudah menjadikannya tempat yang ideal untuk beribadah dan berkumpul dengan komunitas. Selain itu, masjid ini juga menjadi landmark penting di Bengkulu, sering dikunjungi oleh wisatawan yang ingin merasakan suasana spiritual dan budaya lokal.', 'latitude' => '-3.8612', 'longitude' => '102.3135'],
            ['id_fasilitas' => 'F035', 'id_pariwisata' => 'P032', 'nama_fasilitas' => 'Hotel Puri Indah', 'lokasi' => 'Jalan Indah No. 2, Kota Bengkulu', 'jenis' => 'Hotel', 'deskripsi' => 'Hotel Puri Indah adalah hotel yang nyaman dan modern dengan fasilitas lengkap, termasuk restoran dan layanan spa untuk para tamu. Dengan lokasi yang strategis, hotel ini menawarkan akses mudah ke berbagai tempat wisata di Bengkulu. Setiap kamar dirancang untuk memberikan kenyamanan maksimal, menjadikannya pilihan yang ideal bagi wisatawan yang ingin menikmati pengalaman menginap yang menyenangkan.', 'latitude' => '-3.8601', 'longitude' => '102.3143'],
            ['id_fasilitas' => 'F036', 'id_pariwisata' => 'P033', 'nama_fasilitas' => 'Taman Hiburan Rakyat', 'lokasi' => 'Jalan Hiburan No. 10, Kota Bengkulu', 'jenis' => 'Tempat Ibadah', 'deskripsi' => 'Taman Hiburan Rakyat adalah tempat hiburan yang menawarkan berbagai permainan untuk anak-anak dan keluarga, serta ruang terbuka hijau yang nyaman. Dengan berbagai fasilitas yang menyenangkan, taman ini menjadi pilihan yang tepat untuk menghabiskan waktu bersama keluarga dan teman-teman, menjadikan setiap kunjungan penuh dengan keceriaan dan kebahagiaan.', 'latitude' => '-3.8590', 'longitude' => '102.3155'],
            ['id_fasilitas' => 'F037', 'id_pariwisata' => 'P034', 'nama_fasilitas' => 'Restoran Tepi Laut', 'lokasi' => 'Jalan Laut Raya No. 5, Kota Bengkulu', 'jenis' => 'Restoran', 'deskripsi' => 'Restoran Tepi Laut menawarkan pengalaman bersantap yang unik dengan pemandangan laut yang menakjubkan. Menyajikan hidangan laut segar dan berbagai masakan lokal yang menggugah selera, restoran ini menjadi tempat yang sempurna untuk menikmati makanan sambil menikmati keindahan alam. Dengan suasana yang santai dan pelayanan yang ramah, setiap kunjungan ke restoran ini akan menjadi pengalaman yang tak terlupakan.', 'latitude' => '-3.8609', 'longitude' => '102.3125'],
            ['id_fasilitas' => 'F038', 'id_pariwisata' => 'P035', 'nama_fasilitas' => 'Hotel Pantai Sejahtera', 'lokasi' => 'Jalan Pantai No. 12, Kota Bengkulu', 'jenis' => 'Hotel', 'deskripsi' => 'Hotel Pantai Sejahtera adalah hotel dengan lokasi strategis di tepi pantai, menawarkan pemandangan laut yang indah dan layanan kelas satu. Dengan berbagai fasilitas yang dirancang untuk kenyamanan tamu, hotel ini menjadi pilihan yang ideal bagi wisatawan yang ingin menikmati liburan yang santai dan menyenangkan. Setiap kamar dilengkapi dengan fasilitas modern untuk memastikan pengalaman menginap yang memuaskan.', 'latitude' => '-3.8604', 'longitude' => '102.3148'],
            ['id_fasilitas' => 'F039', 'id_pariwisata' => 'P036', 'nama_fasilitas' => 'Restoran Sriwijaya', 'lokasi' => 'Jalan Raya No. 3, Kota Bengkulu', 'jenis' => 'Restoran', 'deskripsi' => 'Restoran Sriwijaya menawarkan berbagai hidangan khas Bengkulu dengan citarasa yang autentik. Dengan suasana yang nyaman dan pelayanan yang ramah, restoran ini menjadi tempat yang ideal untuk makan bersama keluarga. Menu yang ditawarkan selalu menggunakan bahan-bahan segar dan berkualitas tinggi, memberikan pengalaman bersantap yang memuaskan bagi setiap pengunjung.', 'latitude' => '-3.8600', 'longitude' => '102.3120'],
            ['id_fasilitas' => 'F040', 'id_pariwisata' => 'P030', 'nama_fasilitas' => 'Toko Kerajinan Batik', 'lokasi' => 'J alan Batik No. 3, Kota Bengkulu', 'jenis' => 'Oleh-oleh', 'deskripsi' => 'Toko Kerajinan Batik adalah tempat yang menawarkan berbagai kerajinan tangan khas Bengkulu, termasuk batik dan produk kerajinan lokal lainnya. Dengan suasana yang hangat dan pelayanan yang baik, Anda dapat menemukan oleh-oleh yang sempurna untuk dibawa pulang sebagai kenang-kenangan dari perjalanan Anda. Toko ini juga sering menjadi tempat bagi wisatawan untuk belajar lebih banyak tentang seni batik dan proses pembuatannya, menjadikannya pengalaman yang mendidik sekaligus menyenangkan.', 'latitude' => '-3.8592', 'longitude' => '102.3115'],
            ['id_fasilitas' => 'F041', 'id_pariwisata' => 'P035', 'nama_fasilitas' => 'Warung Sate Bengkulu', 'lokasi' => 'Jalan Sate No. 5, Kota Bengkulu', 'jenis' => 'Restoran', 'deskripsi' => 'Warung Sate Bengkulu adalah tempat yang menyajikan sate khas Bengkulu dengan berbagai pilihan daging dan bumbu khas yang menggugah selera. Dengan suasana yang sederhana namun nyaman, warung ini menjadi pilihan yang tepat untuk menikmati hidangan yang lezat dan autentik. Setiap tusuk sate disajikan dengan bumbu yang kaya rasa, menjadikannya favorit di kalangan penduduk lokal dan wisatawan.', 'latitude' => '-3.8585', 'longitude' => '102.3100'],
            ['id_fasilitas' => 'F042', 'id_pariwisata' => 'P034', 'nama_fasilitas' => 'Kedai Mie Bengkulu', 'lokasi' => 'Jalan Mie No. 4, Kota Bengkulu', 'jenis' => 'Restoran', 'deskripsi' => 'Kedai Mie Bengkulu menyajikan mie khas Bengkulu dengan berbagai jenis topping dan sambal khas daerah setempat. Dengan suasana yang ramah dan pelayanan yang cepat, kedai ini menjadi tempat yang ideal untuk menikmati hidangan mie yang lezat dan memuaskan. Menu yang ditawarkan selalu menggunakan bahan-bahan segar, memberikan cita rasa yang autentik dan menggugah selera.', 'latitude' => '-3.8607', 'longitude' => '102.3108'],
            ['id_fasilitas' => 'F043', 'id_pariwisata' => 'P012', 'nama_fasilitas' => 'Hotel Surya', 'lokasi' => 'Jalan Surya No. 7, Kota Bengkulu', 'jenis' => 'Hotel', 'deskripsi' => 'Hotel Surya adalah hotel dengan fasilitas lengkap seperti kolam renang dan restoran, ideal untuk keluarga dan pebisnis yang berkunjung ke Bengkulu. Dengan pelayanan yang ramah dan suasana yang nyaman, hotel ini menjadi pilihan yang tepat untuk menginap. Setiap kamar dirancang untuk memberikan kenyamanan maksimal, menjadikannya tempat yang sempurna untuk beristirahat setelah seharian beraktivitas.', 'latitude' => '-3.8613', 'longitude' => '102.3110'],
            ['id_fasilitas' => 'F044', 'id_pariwisata' => 'P011', 'nama_fasilitas' => 'Restoran Dapoer', 'lokasi' => 'Jalan Dapoer No. 6, Kota Bengkulu', 'jenis' => 'Restoran', 'deskripsi' => 'Restoran Dapoer menyajikan masakan rumah khas Bengkulu dengan bahan-bahan segar dan rasa autentik yang menggugah selera. Dengan suasana yang hangat dan pelayanan yang baik, restoran ini menjadi tempat yang ideal untuk makan bersama keluarga. Menu yang ditawarkan selalu menggunakan resep tradisional, memberikan pengalaman bersantap yang memuaskan bagi setiap pengunjung.', 'latitude' => '-3.8618', 'longitude' => '102.3102'],
            ['id_fasilitas' => 'F045', 'id_pariwisata' => 'P012', 'nama_fasilitas' => 'Toko Kain Batik', 'lokasi' => 'Jalan Batik No. 5, Kota Bengkulu', 'jenis' => 'Oleh-oleh', 'deskripsi' => 'Toko Kain Batik adalah tempat yang menjual kain batik khas Bengkulu dengan motif tradisional dan modern yang cocok untuk oleh-oleh atau pakaian sehari-hari. Dengan suasana yang ramah dan pelayanan yang baik, Anda dapat menemukan berbagai pilihan kain batik yang berkualitas tinggi, menjadikannya tempat yang ideal untuk berbelanja oleh-oleh.', 'latitude' => '-3 .8600', 'longitude' => '102.3093'],
            ['id_fasilitas' => 'F046', 'id_pariwisata' => 'P013', 'nama_fasilitas' => 'Toko Perhiasan Cempaka', 'lokasi' => 'Jalan Cempaka No. 2, Kota Bengkulu', 'jenis' => 'Oleh-oleh', 'deskripsi' => 'Toko Perhiasan Cempaka menawarkan berbagai perhiasan khas Bengkulu, mulai dari kalung, gelang hingga cincin dengan desain tradisional dan modern. Dengan suasana yang nyaman dan pelayanan yang ramah, Anda dapat menemukan perhiasan yang sempurna untuk dibawa pulang sebagai kenang-kenangan dari perjalanan Anda. Toko ini juga sering menjadi tempat bagi wisatawan untuk belajar lebih banyak tentang kerajinan perhiasan lokal.', 'latitude' => '-3.8604', 'longitude' => '102.3087'],
            ['id_fasilitas' => 'F047', 'id_pariwisata' => 'P005', 'nama_fasilitas' => 'Warung Makan Jaya', 'lokasi' => 'Jalan Raya Jakat No. 4, Kota Bengkulu','jenis' => 'Restoran','deskripsi' => 'Warung Makan Jaya adalah tempat makan yang sangat terkenal di Kota Bengkulu, dikenal dengan hidangan ikan bakar dan seafood yang segar. Dengan suasana yang sederhana namun nyaman, warung ini menjadi pilihan favorit bagi penduduk lokal dan wisatawan. Menu andalan mereka adalah ikan bakar yang diolah dengan bumbu khas yang kaya rasa, serta berbagai pilihan hidangan laut lainnya seperti cumi-cumi dan udang. Selain itu, warung ini juga menyajikan berbagai hidangan pendamping yang menggugah selera, seperti sambal terasi dan sayur segar yang diambil dari kebun lokal. Dengan harga yang terjangkau dan pelayanan yang ramah, Warung Makan Jaya adalah tempat yang ideal untuk menikmati hidangan lezat bersama keluarga dan teman-teman. Warung ini buka setiap hari dari pukul 10:00 hingga 22:00, memberikan kesempatan bagi pengunjung untuk menikmati makan siang atau makan malam. Suasana yang hangat dan bersahabat membuat setiap kunjungan menjadi pengalaman yang menyenangkan, dan sering kali pengunjung merasa betah untuk berlama-lama sambil menikmati makanan dan bercengkerama. Lokasi strategis di tengah kota memudahkan akses bagi siapa saja yang ingin menikmati hidangan lezat setelah berkeliling menjelajahi tempat-tempat wisata di Bengkulu. Dengan semua keunggulan ini, Warung Makan Jaya menjadi salah satu destinasi kuliner yang wajib dikunjungi bagi siapa saja yang berada di Bengkulu.', 'latitude' => '-3.8040','longitude' => '102.2650',],
            ['id_fasilitas' => 'F048', 'id_pariwisata' => 'P014', 'nama_fasilitas' => 'Restoran Laut Biru', 'lokasi' => 'Jalan Laut Raya No. 3, Kota Bengkulu', 'jenis' => 'Restoran', 'deskripsi' => 'Restoran Laut Biru menyajikan hidangan laut segar dan masakan lokal dengan pemandangan laut yang indah. Dengan suasana yang santai dan pelayanan yang ramah, restoran ini menjadi tempat yang sempurna untuk menikmati makanan sambil menikmati keindahan alam. Menu yang ditawarkan mencakup berbagai pilihan hidangan laut yang lezat, menjadikannya favorit di kalangan penduduk lokal dan wisatawan.', 'latitude' => '-3.8611', 'longitude' => '102.3091'],
            ['id_fasilitas' => 'F049', 'id_pariwisata' => 'P015', 'nama_fasilitas' => 'Hotel Bukit Indah', 'lokasi' => 'Jalan Bukit No. 8, Kota Bengkulu', 'jenis' => 'Hotel', 'deskripsi' => 'Hotel Bukit Indah adalah hotel dengan pemandangan indah, menawarkan berbagai layanan kamar, kolam renang, dan restoran dengan menu internasional. Dengan lokasi yang strategis, hotel ini memberikan akses mudah ke berbagai destinasi wisata di Bengkulu. Setiap kamar dirancang untuk memberikan kenyamanan maksimal, menjadikannya pilihan yang ideal bagi wisatawan yang ingin menikmati pengalaman menginap yang menyenangkan.', 'latitude' => '-3.8616', 'longitude' => '102.3079'],
            ['id_fasilitas' => 'F050', 'id_pariwisata' => 'P016', 'nama_fasilitas' => 'Masjid Agung At-Taqwa', 'lokasi' => 'Jalan At-Taqwa No. 5, Kota Bengkulu', 'jenis' => 'Tempat Ibadah', 'deskripsi' => 'Masjid Agung At-Taqwa adalah masjid besar yang menjadi salah satu landmark religi di Bengkulu, dengan arsitektur megah dan sering digunakan untuk kegiatan keagamaan. Lingkungan yang tenang dan damai menjadikannya tempat yang ideal untuk beribadah dan merenung. Masjid ini juga sering mengadakan berbagai kegiatan sosial dan keagamaan, menjadikannya pusat komunitas bagi umat Muslim di Bengkulu.', 'latitude' => '-3.8620', 'longitude' => '102.3068']
        ]);
    }
}