<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PariwisataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pariwisata')->insert([
            ['id_pariwisata' => 'P001', 'nama_pariwisata' => 'Pantai Panjang', 'lokasi' => 'Jl. Pantai Panjang No. 1, Kota Bengkulu', 'deskripsi' => 'Pantai Panjang adalah destinasi wisata yang terkenal di Kota Bengkulu, menawarkan panorama laut yang luas dengan pasir putih yang lembut. Suasana pantai yang tenang dan air laut yang jernih menjadikannya tempat yang ideal untuk bersantai, berjalan-jalan, atau berjemur. Keindahan alamnya, ditambah dengan fasilitas pendukung seperti warung makanan, menjadikannya tempat yang sangat populer di kalangan wisatawan lokal dan mancanegara.', 'latitude' => '-3.7956', 'longitude' => '102.2675'],
            ['id_pariwisata' => 'P002', 'nama_pariwisata' => 'Taman Kota Bengkulu', 'lokasi' => 'Jl. Jend. Sudirman No. 15, Kota Bengkulu', 'deskripsi' => 'Taman Kota Bengkulu adalah ruang terbuka hijau yang luas yang terletak di pusat kota. Tempat ini menawarkan area yang teduh dengan pohon-pohon besar, taman bunga yang indah, dan jalur pejalan kaki yang nyaman. Ini adalah tempat yang sempurna untuk piknik keluarga, berolahraga, atau hanya menikmati waktu senggang sambil menikmati udara segar di tengah kota yang sibuk.', 'latitude' => '-3.8032', 'longitude' => '102.2638'],
            ['id_pariwisata' => 'P003', 'nama_pariwisata' => 'Benteng Marlborough', 'lokasi' => 'Jl. Benteng No. 23, Kota Bengkulu', 'deskripsi' => 'Benteng Marlborough adalah situs bersejarah yang dibangun oleh Inggris pada abad ke-18. Benteng ini, yang dulunya digunakan sebagai pos pertahanan, kini menjadi salah satu tujuan wisata utama di Bengkulu. Pengunjung dapat menjelajahi struktur benteng yang kokoh, menikmati pemandangan laut yang memukau, serta mempelajari sejarah kolonial Inggris di Indonesia.', 'latitude' => '-3.8035', 'longitude' => '102.2650'],
            ['id_pariwisata' => 'P004', 'nama_pariwisata' => 'Air Terjun Curug 7', 'lokasi' => 'Jl. Air Terjun No. 7, Desa Curug, Bengkulu', 'deskripsi' => 'Air Terjun Curug 7 dikenal karena keindahan alamnya yang menakjubkan. Tersembunyi di tengah hutan tropis, air terjun ini terdiri dari tujuh tingkatan yang mempesona. Suara gemericik air yang jatuh, udara sejuk, dan pemandangan hijau yang mengelilingi membuat tempat ini sangat cocok untuk petualangan dan berfoto. Lokasinya yang jauh dari keramaian memberikan ketenangan bagi para pengunjung.', 'latitude' => '-3.7931', 'longitude' => '102.2356'],
            ['id_pariwisata' => 'P005', 'nama_pariwisata' => 'Pantai Tapak Paderi', 'lokasi' => 'Jl. Tapak Paderi No. 5, Kota Bengkulu', 'deskripsi' => 'Pantai Tapak Paderi adalah pantai yang menawarkan suasana tenang dan pemandangan laut yang menawan. Pasir pantainya yang bersih dan air lautnya yang jernih cocok untuk berenang, berjemur, atau bermain pasir. Lokasi yang dekat dengan pusat kota menjadikannya mudah diakses oleh wisatawan yang ingin menikmati suasana pantai tanpa harus pergi jauh dari kota.', 'latitude' => '-3.7950', 'longitude' => '102.2600'],
            ['id_pariwisata' => 'P006', 'nama_pariwisata' => 'Monumen Bung Karno', 'lokasi' => 'Jl. Bung Karno No.  10, Kota Bengkulu', 'deskripsi' => 'Monumen Bung Karno adalah simbol penting bagi perjuangan kemerdekaan Indonesia, dibangun untuk mengenang peran besar Presiden pertama, Soekarno, selama pengasingannya di Bengkulu. Monumen ini terletak di taman yang rimbun dengan pemandangan kota yang indah. Pengunjung dapat mempelajari lebih dalam sejarah perjuangan Indonesia di tempat bersejarah ini.', 'latitude' => '-3.8034', 'longitude' => '102.2690'],
            ['id_pariwisata' => 'P007', 'nama_pariwisata' => 'Museum Negeri Bengkulu', 'lokasi' => 'Jl. Jenderal Sudirman No. 5, Kota Bengkulu', 'deskripsi' => 'Museum Negeri Bengkulu adalah tempat yang tepat untuk memahami sejarah, budaya, dan tradisi daerah Bengkulu. Di museum ini, pengunjung dapat melihat berbagai koleksi artefak, benda-benda sejarah, dan karya seni yang menggambarkan kehidupan masyarakat Bengkulu dari masa lalu hingga kini. Museum ini juga memberikan wawasan tentang perkembangan daerah dan pengaruh berbagai budaya yang ada.', 'latitude' => '-3.8050', 'longitude' => '102.2630'],
            ['id_pariwisata' => 'P008', 'nama_pariwisata' => 'Pantai Sungai Suci', 'lokasi' => 'Jl. Sungai Suci, Bengkulu', 'deskripsi' => 'Pantai Sungai Suci adalah destinasi yang ideal untuk berlibur, dengan keindahan pantai yang alami dan jauh dari keramaian. Kejernihan air lautnya membuatnya cocok untuk berenang atau snorkeling. Tempat ini juga menawarkan suasana yang tenang, dengan pohon-pohon kelapa yang tumbuh di sepanjang pantai, memberikan tempat yang sempurna untuk bersantai dan menikmati alam.', 'latitude' => '-3.7892', 'longitude' => '102.2335'],
            ['id_pariwisata' => 'P009', 'nama_pariwisata' => 'Pasar Tradisional Bengkulu', 'lokasi' => 'Jl. Pasar No. 3, Kota Bengkulu', 'deskripsi' => 'Pasar Tradisional Bengkulu adalah pasar yang menawarkan berbagai produk lokal, mulai dari makanan tradisional hingga kerajinan tangan. Pasar ini merupakan tempat yang cocok untuk merasakan kehidupan lokal dan membeli oleh-oleh khas Bengkulu. Pengunjung bisa merasakan suasana pasar yang hidup dan berinteraksi langsung dengan penduduk setempat yang ramah.', 'latitude' => '-3.8036', 'longitude' => '102.2684'],
            ['id_pariwisata' => 'P010', 'nama_pariwisata' => 'Pulau Tikus', 'lokasi' => 'Pulau Tikus, Bengkulu', 'deskripsi' => 'Pulau Tikus adalah pulau kecil yang terletak di lepas pantai Kota Bengkulu. Dengan pasir putihnya yang bersih dan perairan yang jernih, pulau ini menawarkan tempat yang sempurna untuk kegiatan snorkeling dan menyelam. Keindahan bawah laut yang kaya dengan kehidupan terumbu karang menjadi daya tarik utama bagi para pengunjung yang menyukai kegiatan petualangan bawah laut.', 'latitude' => '-3.8250', 'longitude' => '102.2900'],
            ['id_pariwisata' => 'P011', 'nama_pariwisata' => 'Taman Wisata Alam Bukit Daun', 'lokasi' => 'Jl. Bukit Daun, Kota Bengkulu', 'deskripsi' => 'Taman Wisata Alam Bukit Daun merupakan tempat yang sangat ideal bagi pecinta alam dan petualangan. Dikelilingi oleh hutan tropis yang lebat, taman ini menawarkan berbagai jalur trekking yang menantang serta pemandangan alam yang memukau. Pengunjung dapat menikmati suasana segar dan keindahan flora dan fauna sambil menjelajahi berbagai sudut taman.', 'latitude' => '-3.8072', 'longitude' => '102.2615'],
            ['id_pariwisata' => 'P012', 'nama_pariwisata' => 'Danau Dendam Tak Sudah', 'lokasi' => 'Jl. Danau Dendam No. 4, Bengkulu', 'deskripsi' => 'Danau Dendam Tak Sudah adalah danau dengan cerita legendaris yang menyelimuti kisah sejarah daerah ini. Selain keindahan alam yang menakjubkan, danau ini juga memiliki nilai budaya yang sangat kental, yang sering dikunjungi oleh wisatawan yang tertarik pada mitos dan sejarah lokal. Tempat ini sangat cocok untuk piknik , berenang, atau menikmati pemandangan sekitar.', 'latitude' => '-3.8101', 'longitude' => '102.2702'],
            ['id_pariwisata' => 'P013', 'nama_pariwisata' => 'Pantai Nala', 'lokasi' => 'Jl. Pantai Nala No. 1, Bengkulu', 'deskripsi' => 'Pantai Nala memiliki pesona alam yang luar biasa dengan pasir putih yang lembut dan air laut yang jernih. Pantai ini cocok bagi pengunjung yang ingin menikmati suasana tenang sambil menikmati keindahan laut. Selain itu, pantai ini juga dikenal sebagai tempat yang cocok untuk aktivitas memancing dan berlayar.', 'latitude' => '-3.8085', 'longitude' => '102.2620'],
            ['id_pariwisata' => 'P014', 'nama_pariwisata' => 'Taman Nasional Bukit Barisan Selatan', 'lokasi' => 'Taman Nasional Bukit Barisan, Bengkulu', 'deskripsi' => 'Taman Nasional Bukit Barisan Selatan adalah kawasan konservasi yang kaya akan flora dan fauna, dengan hutan tropis yang lebat dan beragam satwa endemik. Tempat ini sangat cocok bagi para pecinta alam dan wisatawan yang ingin melakukan trekking, berpetualang, dan menikmati keindahan alam yang masih alami.', 'latitude' => '-3.8110', 'longitude' => '102.2830'],
            ['id_pariwisata' => 'P015', 'nama_pariwisata' => 'Pulau Enggano', 'lokasi' => 'Pulau Enggano, Bengkulu', 'deskripsi' => 'Pulau Enggano adalah pulau yang masih sangat alami, jauh dari keramaian. Pulau ini menawarkan pesona alam yang sangat indah, dengan pantai yang eksotis dan pemandangan yang menakjubkan. Pulau ini juga memiliki berbagai keanekaragaman hayati, menjadikannya destinasi yang menarik untuk pecinta alam dan penggemar petualangan.', 'latitude' => '-3.7200', 'longitude' => '102.3500'],
            ['id_pariwisata' => 'P016', 'nama_pariwisata' => 'Pantai Teluk Segara', 'lokasi' => 'Jl. Teluk Segara No. 9, Bengkulu', 'deskripsi' => 'Pantai Teluk Segara menawarkan pemandangan yang menakjubkan dengan pasir putih yang luas dan laut yang tenang. Pantai ini adalah tempat yang sempurna untuk bersantai, berenang, atau menikmati matahari terbenam yang indah. Dengan suasana yang tenang, pantai ini sangat cocok untuk keluarga dan wisatawan yang mencari ketenangan.', 'latitude' => '-3.7941', 'longitude' => '102.2543'],
            ['id_pariwisata' => 'P017', 'nama_pariwisata' => 'Kebun Raya Bengkulu', 'lokasi' => 'Jl. Kebun Raya No. 2, Kota Bengkulu', 'deskripsi' => 'Kebun Raya Bengkulu adalah tempat yang nyaman dan sejuk untuk berjalan-jalan di tengah taman yang rimbun dengan berbagai jenis flora. Di sini, pengunjung bisa menikmati udara segar, melihat berbagai koleksi tanaman tropis, dan menikmati suasana hijau yang asri. Kebun ini juga sering digunakan untuk berbagai kegiatan edukasi dan rekreasi.', 'latitude' => '-3.8064', 'longitude' => '102.2714'],
            ['id_pariwisata' => 'P018', 'nama_pariwisata' => 'Pusat Informasi Wisata Bengkulu', 'lokasi' => 'Jl. Wisata No. 5, Kota Bengkulu', 'deskripsi' => 'Pusat Informasi Wisata Bengkulu adalah tempat yang menyediakan berbagai informasi tentang destinasi wisata di Bengkulu. Di sini, pengunjung dapat menemukan brosur, peta, dan panduan yang berguna untuk merencanakan perjalanan mereka. Pusat ini juga menawarkan tips dan rekomendasi untuk mengeksplorasi keindahan alam dan budaya Bengkulu dengan lebih baik.', 'latitude' => '-3.8035', 'longitude' => '102.2695'],
            ['id_pariwisata' => 'P019', 'nama_pariwisata' => 'Gua Maria Bukit Siapi-api', 'lokasi' => 'Jl. Bukit Siapi-api No. 8, Bengkulu', 'deskripsi' => 'Gua Maria Bukit Siapi-api adalah salah satu tempat ziarah yang sangat dihormati di Bengkulu. Selain sebagai tempat ibadah, gua ini juga memiliki pemandangan yang sangat indah. Suasana yang tenang dan penuh ketenangan menjadikan tempat ini sangat cocok bagi mereka yang ingin melakukan refleksi spiritual atau sekadar menikmati kedamaian alam sekitar.', 'latitude' => '-3.7925', 'longitude' => '102.2655'],
            ['id_pariwisata' => 'P020', 'nama_pariwisata' => 'Pantai Pasir Putih', 'lokasi' => 'Jl. Pasir Putih No. 7, Bengkulu', 'deskripsi' => 'Pantai Pasir Putih menawarkan keindahan alam dengan hamparan pasir putih yang luas dan air laut yang jernih. Tempat ini sangat cocok untuk berjemur, bermain air, atau melakukan aktivitas pantai lainnya. Pantai ini juga dikenal karena suasananya yang tenang, menjadikannya tempat ideal untuk bersantai sambil menikmati pemandangan laut yang menakjubkan.', 'latitude' => '-3.8200', 'longitude' => '102.2900'],
            ['id_pariwisata' => 'P021', 'nama_pariwisata' => 'Air Terjun Seven Waterfall', 'lokasi' => 'Kecamatan Lebong, Bengkulu', 'deskripsi' => 'Air Terjun Seven Waterfall adalah serangkaian air terjun yang menawarkan keindahan alam luar biasa. Tujuh air terjun yang mengalir di antara bebatuan hijau menciptakan pemandangan yang spektakuler, menjadikannya destinasi yang sangat dicari oleh pecinta alam dan petualangan. Tempat ini cocok untuk kegiatan trekking dan menikmati keindahan alam yang masih asri.', 'latitude' => '-3.8452', 'longitude' => '102.2689'],
            ['id_pariwisata' => 'P022', 'nama_pariwisata' => 'Pantai Sungai Suci', 'lokasi' => 'Jl. Sungai Suci, Bengkulu', 'deskripsi' => 'Pantai Sungai Suci adalah tempat yang ideal bagi mereka yang ingin menikmati suasana pantai yang tenang. Dikenal dengan air laut yang jernih dan pasir putihnya yang lembut, pantai ini juga populer di kalangan wisatawan yang suka memancing atau hanya menikmati matahari terbenam. Keindahan alamnya yang alami menjadikan pantai ini sangat menarik untuk dikunjungi.', 'latitude' => '-3.8209', 'longitude' => '102.2747'],
            ['id_pariwisata' => 'P023', 'nama_pariwisata' => 'Bukit Bungkuk', 'lokasi' => 'Kecamatan Bungkuk, Bengkulu', 'deskripsi' => 'Bukit Bungkuk menawarkan pemandangan alam yang luar biasa dari ketinggian. Dengan jalur pendakian yang cukup menantang, bukit ini menjadi tujuan favorit bagi para pendaki dan pecinta alam. Sesampainya di puncak, pengunjung akan disuguhkan dengan panorama alam yang memukau, dengan latar belakang kota Bengkulu dan laut yang membentang.', 'latitude' => '-3.8022', 'longitude' => '102.2811'],
            ['id_pariwisata' => 'P024', 'nama_pariwisata' => 'Hutan Lindung Bukit Barisan', 'lokasi' => 'Taman Nasional Bukit Barisan, Bengkulu', 'deskripsi' => 'Hutan Lindung Bukit Barisan adalah salah satu kawasan konservasi yang kaya akan flora dan fauna langka. Dengan jalur pendakian yang memadai dan udara yang segar, hutan ini menawarkan kesempatan bagi pengunjung untuk melakukan trekking sambil menikmati keanekaragaman hayati. Hutan ini juga cocok untuk kegiatan observasi alam dan fotografi.', 'latitude' => '-3.8185', 'longitude' => '102.2934'],
            ['id_pariwisata' => 'P025', 'nama_pariwisata' => 'Taman Wisata Alam Bengkulu', 'lokasi' => 'Jl. Wisata Alam, Bengkulu', 'deskripsi' => 'Taman Wisata Alam Bengkulu adalah tempat yang menyajikan pengalaman alam yang menyegarkan. Taman ini memiliki berbagai fasilitas untuk wisata keluarga, termasuk jalur jalan setapak yang nyaman, area piknik, dan berbagai spot foto yang indah. Selain itu, taman ini juga menjadi rumah bagi berbagai jenis flora dan fauna tropis.', 'latitude' => '-3.8010', 'longitude' => '102.2777'],
            ['id_pariwisata' => 'P026', 'nama_pariwisata' => 'Pantai Berlian', 'lok asi' => 'Jl. Berlian No. 6, Bengkulu', 'deskripsi' => 'Pantai Berlian adalah pantai dengan pemandangan yang sangat memukau, dengan pasir yang bersih dan air laut yang biru. Tempat ini cocok untuk berlibur dengan keluarga atau teman-teman, menikmati aktivitas air, atau sekadar bersantai di bawah pohon kelapa. Keindahannya yang alami menjadikan pantai ini populer di kalangan wisatawan.', 'latitude' => '-3.8123', 'longitude' => '102.2832'],
            ['id_pariwisata' => 'P027', 'nama_pariwisata' => 'Danau Raya', 'lokasi' => 'Jl. Raya Danau, Bengkulu', 'deskripsi' => 'Danau Raya adalah danau yang menawarkan pemandangan alam yang mempesona, dengan air yang tenang dan dikelilingi oleh pepohonan hijau. Danau ini menjadi tempat yang populer untuk berbagai kegiatan outdoor seperti berperahu, berkemah, atau hanya menikmati suasana alam yang tenang. Tempat ini sangat cocok untuk piknik keluarga atau para wisatawan yang ingin merasakan ketenangan.', 'latitude' => '-3.8047', 'longitude' => '102.2665'],
            ['id_pariwisata' => 'P028', 'nama_pariwisata' => 'Pemandian Air Panas Rindu Alam', 'lokasi' => 'Jl. Rindu Alam, Bengkulu', 'deskripsi' => 'Pemandian Air Panas Rindu Alam menawarkan pengalaman relaksasi dengan mandi air panas yang dipercaya memiliki manfaat kesehatan. Dikelilingi oleh alam yang sejuk dan pemandangan yang hijau, tempat ini menjadi destinasi yang sempurna untuk melepaskan stres dan menikmati ketenangan. Air panasnya berasal dari sumber alami yang kaya akan mineral.', 'latitude' => '-3.8104', 'longitude' => '102.2592'],
            ['id_pariwisata' => 'P029', 'nama_pariwisata' => 'Taman Laut Enggano', 'lokasi' => 'Pulau Enggano, Bengkulu', 'deskripsi' => 'Taman Laut Enggano adalah kawasan wisata bawah laut yang menawarkan keindahan terumbu karang dan kehidupan laut yang luar biasa. Tempat ini cocok untuk snorkeling dan diving, memberikan kesempatan bagi wisatawan untuk menikmati keanekaragaman hayati laut yang masih alami. Taman Laut Enggano juga dikelilingi oleh pantai yang indah dan hutan tropis.', 'latitude' => '-3.7274', 'longitude' => '102.3550'],
            ['id_pariwisata' => 'P030', 'nama_pariwisata' => 'Pantai Pasir Perawan', 'lokasi' => 'Jl. Pasir Perawan No. 2, Bengkulu', 'deskripsi' => 'Pantai Pasir Perawan adalah pantai yang terkenal dengan pasir putihnya yang bersih dan air laut yang jernih. Pantai ini memberikan suasana yang damai dan cocok bagi pengunjung yang ingin menikmati ketenangan sambil bersantai atau berjalan-jalan di sepanjang pantai. Tempat ini juga ideal untuk kegiatan berkemah dan menikmati sunset yang menawan.', 'latitude' => '-3.8190', 'longitude' => '102.2963'],
            ['id_pariwisata' => 'P031', 'nama_pariwisata' => 'Kota Tua Bengkulu', 'lokasi' => 'Jl. Kota Tua, Bengkulu', 'deskripsi' => 'Kota Tua Bengkulu menawarkan pesona sejarah dengan bangunan-bangunan kuno yang masih terawat dengan baik. Berjalan-jalan di sepanjang jalanan Kota Tua akan membawa pengunjung kembali ke masa lalu, melihat arsitektur kolonial dan merasakan nuansa yang tenang. Tempat ini juga memiliki berbagai galeri seni dan museum yang menarik.', 'latitude' => '-3.8049', 'longitude' => '102.2820'],
            ['id_pariwisata' => 'P032', 'nama_pariwisata' => 'Cagar Alam Bukit Tapan', 'lokasi' => 'Bukit Tapan, Bengkulu', 'deskripsi' => 'Cagar Alam Bukit Tapan adalah kawasan konservasi alam yang memiliki beragam flora dan fauna. Dengan jalur trekking yang menantang, pengunjung dapat menjelajahi hutan tropis dan menikmati keindahan alam yang masih alami. Cagar alam ini juga cocok untuk kegiatan birdwatching dan fotografi alam.', 'latitude' => '-3.8029', 'longitude' => '102.2984'],
            ['id_pariwisata' => 'P033', 'nama_pariwisata' => 'Bukit Kelam', 'lokasi' => 'Kecamatan Kelam Permai, Kabupaten Bengkulu', 'deskripsi' => 'Bukit Kelam adalah salah satu tempat wisata alam yang terkenal di Bengkulu. Puncak bukit menawarkan pemandangan spektakuler dari kota dan sekitarnya. Bukit ini dapat diakses melalui jalur pendakian, yang menjadi tantangan menarik bagi para pecinta alam dan wisatawan yang menyukai aktivitas fisik. Di sekitar area ini, pengunjung juga dapat menikmati hutan tropis yang rimbun dan udara yang segar.', 'latitude' => '-3.6333', 'longitude' => '102.2828'],
            ['id_pariwisata' => 'P034', 'nama_pariwisata' => 'Pantai Teluk Sepang', 'lokasi' => 'Teluk Sepang, Bengkulu', 'deskripsi' => 'Pantai Teluk Sepang adalah destinasi wisata alam yang menawarkan keindahan pantai dengan pasir putih dan air laut yang jernih. Tempat ini cocok untuk berenang, memancing, atau sekadar menikmati keindahan alam di sekitar. Suasana yang tenang menjadikan pantai ini populer di kalangan pengunjung yang mencari relaksasi.', 'latitude' => '-3.8101', 'longitude' => '102.2799'],
            ['id_pariwisata' => 'P035', 'nama_pariwisata' => 'Candi Bukit Kaba', 'lokasi' => 'Bukit Kaba, Bengkulu', 'deskripsi' => 'Candi Bukit Kaba adalah situs sejarah yang terletak di puncak bukit dengan pemandangan luar biasa. Candi ini merupakan peninggalan dari masa lalu yang masih terjaga dengan baik. Pengunjung dapat menikmati pemandangan indah dan belajar tentang sejarah serta budaya lokal di sekitar area candi.', 'latitude' => '-3.8161', 'longitude' => '102.2856'],
            ['id_pariwisata' => 'P036', 'nama_pariwisata' => 'Pulau Tikus', 'lokasi' => 'Pulau Tikus, Bengkulu', 'deskripsi' => 'Pulau Tikus adalah sebuah pulau kecil yang terletak di lepas pantai Bengkulu. Dikenal karena pantainya yang indah dan kehidupan laut yang melimpah, tempat ini sangat populer untuk snorkeling dan menyelam. Pulau Tikus juga menyajikan pemandangan yang menakjubkan, cocok untuk para pecinta alam dan wisatawan yang ingin menikmati keindahan alam yang masih alami.', 'latitude' => '-3.8063', 'longitude' => '102.3018'],
        ]);
    }
}